server:
   port: 8080

# db:
#    url: jdbc:mysql://localhost:3306/scheduler_db
#    username: root
#    password: password

worker:
   max: 5
   min: 1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: DTS-HikariPool
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
